### ISSUE TITLE
Overview of updates to the PAKE API

### ISSUE THREAD

**Issue by athoelke** [ARM-software/psa-api#111]
This issue is a collation of the updates planned for the PAKE API. This might help to highlight issues or concerns with the overall plan of action, and track the progress.

- [x] Replace `psa_pake_get_implicit_key()` which outputs to a single key derivation operation, with `psa_pake_get_shared_key()` that outputs as a key. Add an attribute to the ciphersuite that indicates whether the application requires a confirmed, or unconfirmed key from the PAKE. See #100 and #86, and related discussion in #73.
  See #114 (merged)
- [x] Replace the multiple setup functions, `psa_pake_setup()`, `psa_pake_set_role()`, `psa_pake_set_user()`, `psa_pake_set_peer()`, `psa_pake_set_password_key()`, with a single function. This enables correct selection of a driver based on the key. It might be better to just combine the key provision with the setup function? See #89.
  See #115 (merged)
- [x] Add the hash algorithm (from the cipher-suite) to the input and output size macros. See #88.
  ~~See #116~~
  See #124 (merged)
- [x] Allocate asymmetric key types for SPAKE2+, to represent the 'out of band' processed password. See #87 and #73 discussion. This should be aligned with the ideas in #109. Define the key creation methods (KDF), and the import/export formats for the keys. See #73
   See #119
- [x] Add support for selecting a MAC in the PAKE cipher suite
  See #120 (merged)
- [x] Add support for adding additional _context_ data to a PAKE operation
  See #120 (merged)
- [x] Define the 'SPAKE2+ (as used by Matter v1)' algorithm. See #73
  See #129
- [x] Define the 'SPAKE2+ (as described in RFC 9383)' algorithm. See #66 and #73
  See #129

**Comment by athoelke** [comment]
All of these elements have now been completed and merged. This issue is resolved.
